#!/usr/bin/env bash
set -euo pipefail

# ──────────────────────────────────────────────────────────────
# extract-address.sh
#
# Reads the latest Forge broadcast log and extracts the deployed
# ManualNFT contract address, then writes it to frontend/.env.local.
#
# Usage: bash scripts/extract-address.sh
# ──────────────────────────────────────────────────────────────

SCRIPT_NAME="DeployManualNFT"
BROADCAST_DIR="contracts/broadcast/${SCRIPT_NAME}.s.sol"
ENV_FILE="frontend/.env.local"

if [ ! -d "$BROADCAST_DIR" ]; then
  echo "❌ Broadcast directory not found: $BROADCAST_DIR"
  echo "   Make sure you've run a deployment with --broadcast first."
  exit 1
fi

# Find the latest run-latest.json across chain IDs
LATEST=""
for dir in "$BROADCAST_DIR"/*/; do
  candidate="${dir}run-latest.json"
  if [ -f "$candidate" ]; then
    if [ -z "$LATEST" ] || [ "$candidate" -nt "$LATEST" ]; then
      LATEST="$candidate"
    fi
  fi
done

if [ -z "$LATEST" ]; then
  echo "❌ No broadcast logs found in $BROADCAST_DIR"
  exit 1
fi

echo "📖 Reading broadcast log: $LATEST"

# Extract the deployed contract address from the JSON.
# In the transactions array, look for contractAddress (non-null).
CONTRACT_ADDRESS=$(python3 -c "
import json, sys
with open('${LATEST}') as f:
    data = json.load(f)
# Try 'contractAddress' at top-level first
addr = data.get('contractAddress', '')
if not addr:
    # Search transactions for a non-null contractAddress
    for tx in data.get('transactions', []):
        ca = tx.get('contractAddress', '')
        if ca and ca != '0x0000000000000000000000000000000000000000':
            addr = ca
            break
if not addr:
    # Fallback: look in returns for deploy event data
    for tx in data.get('transactions', []):
        if tx.get('transactionType') == 'CREATE':
            addr = tx.get('contractAddress', '')
            break
print(addr)
")

if [ -z "$CONTRACT_ADDRESS" ] || [ "$CONTRACT_ADDRESS" = "0x0000000000000000000000000000000000000000" ]; then
  echo "❌ Could not extract contract address from broadcast log."
  echo "   Raw contents:"
  head -c 2000 "$LATEST"
  exit 1
fi

echo "✅ Extracted contract address: $CONTRACT_ADDRESS"

# ── Write / update frontend/.env.local ───────────────────────
mkdir -p "$(dirname "$ENV_FILE")"

if [ -f "$ENV_FILE" ] && grep -q "^NEXT_PUBLIC_CONTRACT_ADDRESS=" "$ENV_FILE"; then
  # Update existing line
  if [[ "$OSTYPE" == "darwin"* ]]; then
    sed -i '' "s|^NEXT_PUBLIC_CONTRACT_ADDRESS=.*|NEXT_PUBLIC_CONTRACT_ADDRESS=${CONTRACT_ADDRESS}|" "$ENV_FILE"
  else
    sed -i "s|^NEXT_PUBLIC_CONTRACT_ADDRESS=.*|NEXT_PUBLIC_CONTRACT_ADDRESS=${CONTRACT_ADDRESS}|" "$ENV_FILE"
  fi
  echo "✏️  Updated NEXT_PUBLIC_CONTRACT_ADDRESS in ${ENV_FILE}"
elif [ -f "$ENV_FILE" ]; then
  echo "" >> "$ENV_FILE"
  echo "# Added by extract-address.sh" >> "$ENV_FILE"
  echo "NEXT_PUBLIC_CONTRACT_ADDRESS=${CONTRACT_ADDRESS}" >> "$ENV_FILE"
  echo "➕ Added NEXT_PUBLIC_CONTRACT_ADDRESS to ${ENV_FILE}"
else
  cat > "$ENV_FILE" <<EOF
# Auto-generated by extract-address.sh — edit with care
NEXT_PUBLIC_CONTRACT_ADDRESS=${CONTRACT_ADDRESS}
EOF
  echo "📝 Created ${ENV_FILE} with contract address"
fi

echo ""
echo "🚀 Contract address is now configured for the frontend!"
